modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ontime"
version="${version}"
displayName="OnTime"
description="Create custom timers with command execution capabilities. Perfect for minigames, events, or automated server tasks."
authors="MateoF24"

[[mixins]]
config="ontime.client.mixins.json"

[[dependencies.ontime]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"

[[dependencies.ontime]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_range}"
ordering="NONE"
side="BOTH"
